import type { Metadata } from "next";
import { Architects_Daughter, Archivo, Geist, Geist_Mono, Inter, Manrope, Outfit, Patrick_Hand, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin'],
});

const roboto = Roboto({
    weight: ['400', '500', '700'],
    variable: '--font-roboto',
    subsets: ['latin'],
});

const archivo = Archivo({
    variable: '--font-archivo',
    subsets: ['latin'],
});

const patrickHand = Patrick_Hand({
    weight: '400',
    variable: '--font-patrick-hand',
    subsets: ['latin'],
});

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
});

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const architectsDaughter = Architects_Daughter({
    weight: '400',
    variable: '--font-architects-daughter',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${roboto.variable} ${archivo.variable} ${patrickHand.variable} antialiased m-0 p-0 overflow-x-hidden`}
            >
                {children}
            </body>
        </html>
    );
}
